#!/usr/bin/env python3
"""ReceiptRadar supply-chain gate (no network).

Checks:
1. LICENSE + THIRD_PARTY_NOTICES present
2. `cargo metadata` licenses for workspace dependency closure
3. Reject known copyleft-hostile / network-service licenses in the graph
4. Optional: warn if openssl appears in default (non-onnx) graph

Exit 0 = OK. Exit 1 = hard fail. Exit 2 = cargo missing (local only).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

# Hard fail if any package license string contains these (case-insensitive).
FORBIDDEN_SUBSTR = (
    "agpl",
    "sspl",
    "busl",
    "commons clause",
    "elastic license",
    "server side public license",
)

# Soft note only (print, do not fail) — dual-licensed OK if MIT/Apache present.
NOTES_SUBSTR = ("gpl-3.0-only", "gpl-2.0-only")


def repo_root() -> Path:
    here = Path(__file__).resolve().parent
    # tools/supply-chain → repo root
    return here.parent.parent


def require_files(root: Path) -> list[str]:
    errs = []
    for rel in ("LICENSE", "THIRD_PARTY_NOTICES"):
        p = root / rel
        if not p.is_file() or p.stat().st_size < 32:
            errs.append(f"missing or empty: {rel}")
    return errs


def cargo_metadata(root: Path) -> dict:
    cmd = [
        "cargo",
        "metadata",
        "--format-version",
        "1",
        "--no-deps",
    ]
    # Prefer full graph for license scan:
    cmd = ["cargo", "metadata", "--format-version", "1", "--locked"]
    env = os.environ.copy()
    # Avoid interactive rustup prompts in CI.
    env.setdefault("CARGO_TERM_COLOR", "never")
    r = subprocess.run(
        cmd,
        cwd=root,
        capture_output=True,
        text=True,
        env=env,
    )
    if r.returncode != 0:
        raise RuntimeError(f"cargo metadata failed:\n{r.stderr or r.stdout}")
    return json.loads(r.stdout)


def resolve_workspace_package_ids(meta: dict) -> set[str]:
    ws = set(meta.get("workspace_members") or [])
    return ws


def closure_package_ids(meta: dict) -> set[str]:
    """Packages reachable from workspace members (default features)."""
    nodes = {n["id"]: n for n in meta.get("resolve", {}).get("nodes", [])}
    members = set(meta.get("workspace_members") or [])
    seen: set[str] = set()
    stack = list(members)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        node = nodes.get(pid)
        if not node:
            continue
        for dep in node.get("deps", []):
            stack.append(dep["pkg"])
    return seen


def package_map(meta: dict) -> dict[str, dict]:
    return {p["id"]: p for p in meta.get("packages", [])}


def license_of(pkg: dict) -> str:
    lic = pkg.get("license") or ""
    if not lic and pkg.get("license_file"):
        lic = f"file:{pkg['license_file']}"
    return lic.strip()


def scan_licenses(meta: dict) -> tuple[list[str], list[str], list[dict]]:
    """Returns (errors, warnings, inventory rows)."""
    pkgs = package_map(meta)
    ids = closure_package_ids(meta)
    errs: list[str] = []
    warns: list[str] = []
    inv: list[dict] = []
    for pid in sorted(ids):
        p = pkgs.get(pid)
        if not p:
            continue
        name = p.get("name", "?")
        ver = p.get("version", "?")
        lic = license_of(p)
        inv.append({"name": name, "version": ver, "license": lic or "(missing)"})
        low = lic.lower()
        if not lic:
            warns.append(f"missing license field: {name} {ver}")
            continue
        for bad in FORBIDDEN_SUBSTR:
            if bad in low:
                errs.append(f"forbidden license `{lic}`: {name} {ver}")
                break
        for note in NOTES_SUBSTR:
            if note in low and "or" not in low and "apache" not in low and "mit" not in low:
                warns.append(f"strict GPL-only package: {name} {ver} ({lic})")
    # openssl presence in default graph (should be empty for mock CLI path)
    for row in inv:
        if row["name"] in ("openssl", "openssl-sys", "native-tls") and "vendored" not in row[
            "name"
        ]:
            # still warn — policy prefers pure rust crypto for core path
            warns.append(
                f"TLS/openssl-related crate in graph: {row['name']} {row['version']} "
                f"(expected empty for offline core; inspect if unexpected)"
            )
    return errs, warns, inv


def write_inventory(root: Path, inv: list[dict]) -> Path:
    out = root / "docs" / "dependency-inventory.md"
    lines = [
        "# Dependency inventory (generated)",
        "",
        "_Generated by `tools/supply-chain/check_deps.py`. Do not hand-edit._",
        "",
        f"Packages in workspace resolve closure: **{len(inv)}**",
        "",
        "| Crate | Version | License |",
        "|-------|---------|---------|",
    ]
    for row in sorted(inv, key=lambda r: r["name"].lower()):
        lic = row["license"].replace("|", "\\|")
        lines.append(f"| `{row['name']}` | {row['version']} | {lic} |")
    lines.append("")
    lines.append("Policy: see `docs/SUPPLY-CHAIN.md` and `THIRD_PARTY_NOTICES`.")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    root = repo_root()
    write = "--write-inventory" in argv
    quiet = "--quiet" in argv

    file_errs = require_files(root)
    if file_errs:
        for e in file_errs:
            print(f"FAIL | {e}")
        return 1

    try:
        meta = cargo_metadata(root)
    except FileNotFoundError:
        print("FAIL | cargo not found on PATH")
        return 2
    except Exception as e:
        print(f"FAIL | {e}")
        return 1

    errs, warns, inv = scan_licenses(meta)
    if write:
        path = write_inventory(root, inv)
        if not quiet:
            print(f"wrote | {path}")

    if not quiet:
        print(f"packages | {len(inv)}")
        for w in warns:
            print(f"WARN | {w}")
        for e in errs:
            print(f"FAIL | {e}")

    if errs:
        print("SUPPLY_CHAIN_FAIL")
        return 1
    print("SUPPLY_CHAIN_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
