//! Human-readable spending reports (markdown).

use crate::aliases::AliasBook;
use crate::budget::{budget_markdown_section, BudgetBook};
use crate::category::categories_en;
use crate::ledger::{Ledger, LedgerError};
use crate::money::{Iso4217, Money};
use crate::{PRODUCT_ID, VERSION};

/// Build a markdown monthly report for one calendar month.
pub fn monthly_markdown(ledger: &Ledger, year: i32, month: u32) -> Result<String, LedgerError> {
    monthly_markdown_with_budgets(ledger, year, month, &BudgetBook::load())
}

/// Monthly report with an explicit budget book (tests / custom path).
pub fn monthly_markdown_with_budgets(
    ledger: &Ledger,
    year: i32,
    month: u32,
    budgets: &BudgetBook,
) -> Result<String, LedgerError> {
    let ym = format!("{year:04}-{month:02}");
    let by_cur = ledger.stats_by_currency_month(year, month)?;
    let txs = ledger.list_by_month(year, month, 100_000)?;
    let mut out = String::new();
    out.push_str(&format!("# ReceiptRadar report — {ym}\n\n"));
    out.push_str(&format!(
        "_Generated by {PRODUCT_ID} {VERSION}. Local-first. Currencies are never mixed._\n\n"
    ));

    if by_cur.is_empty() {
        out.push_str("No transactions in this month.\n");
        let bud = budget_markdown_section(ledger, budgets, year, month)?;
        out.push_str(&bud);
        return Ok(out);
    }

    out.push_str("## Totals by currency\n\n");
    out.push_str("| Currency | Total | Count |\n|---|---:|---:|\n");
    for s in &by_cur {
        let major = Money::new(
            s.total_minor,
            Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD),
        )
        .display_major();
        out.push_str(&format!("| {} | {} | {} |\n", s.currency, major, s.count));
    }
    out.push('\n');

    let bud = budget_markdown_section(ledger, budgets, year, month)?;
    out.push_str(&bud);

    for s in &by_cur {
        out.push_str(&format!("## Categories ({})\n\n", s.currency));
        let cats = ledger.stats_by_category(&s.currency, Some(&ym))?;
        if cats.is_empty() {
            out.push_str("_none_\n\n");
            continue;
        }
        out.push_str("| Category | Total | Count |\n|---|---:|---:|\n");
        for c in &cats {
            let major = Money::new(
                c.total_minor,
                Iso4217::parse(&c.currency).unwrap_or(Iso4217::TWD),
            )
            .display_major();
            let label = category_label(&c.category);
            out.push_str(&format!(
                "| {} (`{}`) | {} | {} |\n",
                label, c.category, major, c.count
            ));
        }
        out.push('\n');

        out.push_str(&format!("### Top merchants ({})\n\n", s.currency));
        let top = ledger.top_merchants(&s.currency, 10)?;
        out.push_str("| Rank | Merchant | Total | Count |\n|---:|---|---:|---:|\n");
        for (i, (m, minor, cnt)) in top.iter().enumerate() {
            let major = Money::new(*minor, Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD))
                .display_major();
            out.push_str(&format!("| {} | {} | {} | {} |\n", i + 1, m, major, cnt));
        }
        out.push('\n');
    }

    let aliases = AliasBook::load();
    out.push_str("## Transactions\n\n");
    out.push_str("| Date | Merchant | Category | Amount | Id |\n|---|---|---|---:|---|\n");
    for t in &txs {
        let major = Money::new(
            t.amount_minor,
            Iso4217::parse(&t.currency).unwrap_or(Iso4217::TWD),
        )
        .display_major();
        let date = t.transacted_at.get(..10).unwrap_or(&t.transacted_at);
        let merchant = aliases.apply(&t.merchant);
        out.push_str(&format!(
            "| {} | {} | {} | {} {} | `{}` |\n",
            date,
            escape_md(&merchant),
            t.category,
            t.currency,
            major,
            t.id
        ));
    }
    out.push('\n');
    Ok(out)
}

/// Full calendar year report: per-currency year totals + monthly breakdown.
/// Currencies are never mixed. Local-first only.
pub fn annual_markdown(ledger: &Ledger, year: i32) -> Result<String, LedgerError> {
    annual_markdown_with_books(ledger, year, &BudgetBook::load(), &AliasBook::load())
}

/// Annual report with explicit books (tests / custom paths).
pub fn annual_markdown_with_books(
    ledger: &Ledger,
    year: i32,
    budgets: &BudgetBook,
    aliases: &AliasBook,
) -> Result<String, LedgerError> {
    let year_totals = ledger.stats_by_currency_year(year)?;
    let months = ledger.stats_by_currency_year_months(year)?;
    let mut out = String::new();
    out.push_str(&format!("# ReceiptRadar annual report — {year}\n\n"));
    out.push_str(&format!(
        "_Generated by {PRODUCT_ID} {VERSION}. Local-first. Currencies are never mixed._\n\n"
    ));

    if year_totals.is_empty() {
        out.push_str("No transactions in this year.\n");
        return Ok(out);
    }

    out.push_str("## Year totals by currency\n\n");
    out.push_str("| Currency | Total | Count |\n|---|---:|---:|\n");
    for s in &year_totals {
        let major = Money::new(
            s.total_minor,
            Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD),
        )
        .display_major();
        out.push_str(&format!("| {} | {} | {} |\n", s.currency, major, s.count));
    }
    out.push('\n');

    // December budget snapshot (soft limits) — informative for year close.
    let bud = budget_markdown_section(ledger, budgets, year, 12)?;
    if bud.contains('|') {
        out.push_str("## Budgets (December snapshot)\n\n");
        // strip the section header from helper if present
        let body = bud
            .lines()
            .filter(|l| !l.starts_with("## "))
            .collect::<Vec<_>>()
            .join("\n");
        out.push_str(&body);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    for s in &year_totals {
        out.push_str(&format!("## Monthly breakdown ({})\n\n", s.currency));
        out.push_str("| Month | Total | Count |\n|---|---:|---:|\n");
        let cur_months: Vec<_> = months.iter().filter(|m| m.currency == s.currency).collect();
        for m in &cur_months {
            let major = Money::new(
                m.total_minor,
                Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD),
            )
            .display_major();
            out.push_str(&format!(
                "| {:04}-{:02} | {} | {} |\n",
                year, m.month, major, m.count
            ));
        }
        out.push('\n');

        out.push_str(&format!("### Top merchants ({year}, {})\n\n", s.currency));
        // Recompute top within year only
        let txs = ledger.query_transactions(&crate::ledger::TxFilter {
            currency: Some(s.currency.clone()),
            from: Some(format!("{year:04}-01-01")),
            to: Some(format!("{year:04}-12-31")),
            limit: 100_000,
            ..Default::default()
        })?;
        let mut by_merch: std::collections::BTreeMap<String, (i64, i64)> =
            std::collections::BTreeMap::new();
        for t in &txs {
            let name = aliases.apply(&t.merchant);
            let e = by_merch.entry(name).or_insert((0, 0));
            e.0 += t.amount_minor;
            e.1 += 1;
        }
        let mut ranked: Vec<_> = by_merch.into_iter().collect();
        ranked.sort_by_key(|b| std::cmp::Reverse(b.1 .0));
        out.push_str("| Rank | Merchant | Total | Count |\n|---:|---|---:|---:|\n");
        for (i, (m, (minor, cnt))) in ranked.iter().take(15).enumerate() {
            let major = Money::new(*minor, Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD))
                .display_major();
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                i + 1,
                escape_md(m),
                major,
                cnt
            ));
        }
        out.push('\n');
    }
    Ok(out)
}

fn category_label(id: &str) -> String {
    categories_en()
        .into_iter()
        .find(|(i, _)| *i == id)
        .map(|(_, l)| l.to_string())
        .unwrap_or_else(|| id.to_string())
}

fn escape_md(s: &str) -> String {
    s.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ledger::Ledger;
    use crate::money::{Iso4217, Money};
    use crate::types::{Field, FieldSource, ReceiptDraft, SourcePath};

    fn draft_at(id: &str, merchant: &str, minor: i64, date: &str) -> ReceiptDraft {
        ReceiptDraft {
            id: id.into(),
            captured_at: format!("{date}T00:00:00Z"),
            merchant: Field::new(merchant.into(), 1.0, FieldSource::User),
            total: Field::new(Money::new(minor, Iso4217::TWD), 1.0, FieldSource::User),
            transacted_at: Field::new(date.into(), 1.0, FieldSource::User),
            tax: None,
            invoice_id: None,
            category: Field::new("grocery_convenience".into(), 1.0, FieldSource::User),
            raw_text: String::new(),
            ocr_blocks: vec![],
            overall_confidence: 1.0,
            explain: crate::ExplainTrace::new("t", "ocr"),
            source_path: SourcePath::Manual,
        }
    }

    #[test]
    fn report_contains_month() {
        let db = Ledger::open_in_memory().unwrap();
        db.confirm_draft(
            &draft_at("r1", "全家", 8900, "2024-05-01"),
            None,
            None,
            false,
        )
        .unwrap();
        let md = monthly_markdown(&db, 2024, 5).unwrap();
        assert!(md.contains("2024-05"));
        assert!(md.contains("TWD"));
        assert!(md.contains("全家"));
    }

    #[test]
    fn annual_report_spans_months() {
        let db = Ledger::open_in_memory().unwrap();
        db.confirm_draft(
            &draft_at("a", "Store A", 1000, "2024-01-15"),
            None,
            None,
            false,
        )
        .unwrap();
        db.confirm_draft(
            &draft_at("b", "Store B", 2000, "2024-06-01"),
            None,
            None,
            false,
        )
        .unwrap();
        let md = annual_markdown(&db, 2024).unwrap();
        assert!(md.contains("annual report — 2024"), "{md}");
        assert!(md.contains("2024-01") && md.contains("2024-06"), "{md}");
        assert!(md.contains("Year totals"), "{md}");
    }
}
