//! Human-readable spending reports (markdown).

use crate::category::categories_en;
use crate::ledger::{Ledger, LedgerError};
use crate::money::{Iso4217, Money};
use crate::{PRODUCT_ID, VERSION};

/// Build a markdown monthly report for one calendar month.
pub fn monthly_markdown(ledger: &Ledger, year: i32, month: u32) -> Result<String, LedgerError> {
    let ym = format!("{year:04}-{month:02}");
    let by_cur = ledger.stats_by_currency_month(year, month)?;
    let txs = ledger.list_by_month(year, month, 100_000)?;
    let mut out = String::new();
    out.push_str(&format!("# ReceiptRadar report — {ym}\n\n"));
    out.push_str(&format!(
        "_Generated by {PRODUCT_ID} {VERSION}. Local-first. Currencies are never mixed._\n\n"
    ));

    if by_cur.is_empty() {
        out.push_str("No transactions in this month.\n");
        return Ok(out);
    }

    out.push_str("## Totals by currency\n\n");
    out.push_str("| Currency | Total | Count |\n|---|---:|---:|\n");
    for s in &by_cur {
        let major = Money::new(
            s.total_minor,
            Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD),
        )
        .display_major();
        out.push_str(&format!("| {} | {} | {} |\n", s.currency, major, s.count));
    }
    out.push('\n');

    for s in &by_cur {
        out.push_str(&format!("## Categories ({})\n\n", s.currency));
        let cats = ledger.stats_by_category(&s.currency, Some(&ym))?;
        if cats.is_empty() {
            out.push_str("_none_\n\n");
            continue;
        }
        out.push_str("| Category | Total | Count |\n|---|---:|---:|\n");
        for c in &cats {
            let major = Money::new(
                c.total_minor,
                Iso4217::parse(&c.currency).unwrap_or(Iso4217::TWD),
            )
            .display_major();
            let label = category_label(&c.category);
            out.push_str(&format!(
                "| {} (`{}`) | {} | {} |\n",
                label, c.category, major, c.count
            ));
        }
        out.push('\n');

        out.push_str(&format!("### Top merchants ({})\n\n", s.currency));
        let top = ledger.top_merchants(&s.currency, 10)?;
        out.push_str("| Rank | Merchant | Total | Count |\n|---:|---|---:|---:|\n");
        for (i, (m, minor, cnt)) in top.iter().enumerate() {
            let major = Money::new(*minor, Iso4217::parse(&s.currency).unwrap_or(Iso4217::TWD))
                .display_major();
            out.push_str(&format!("| {} | {} | {} | {} |\n", i + 1, m, major, cnt));
        }
        out.push('\n');
    }

    out.push_str("## Transactions\n\n");
    out.push_str("| Date | Merchant | Category | Amount | Id |\n|---|---|---|---:|---|\n");
    for t in &txs {
        let major = Money::new(
            t.amount_minor,
            Iso4217::parse(&t.currency).unwrap_or(Iso4217::TWD),
        )
        .display_major();
        let date = t.transacted_at.get(..10).unwrap_or(&t.transacted_at);
        out.push_str(&format!(
            "| {} | {} | {} | {} {} | `{}` |\n",
            date,
            escape_md(&t.merchant),
            t.category,
            t.currency,
            major,
            t.id
        ));
    }
    out.push('\n');
    Ok(out)
}

fn category_label(id: &str) -> String {
    categories_en()
        .into_iter()
        .find(|(i, _)| *i == id)
        .map(|(_, l)| l.to_string())
        .unwrap_or_else(|| id.to_string())
}

fn escape_md(s: &str) -> String {
    s.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ledger::Ledger;
    use crate::money::{Iso4217, Money};
    use crate::types::{Field, FieldSource, ReceiptDraft, SourcePath};

    #[test]
    fn report_contains_month() {
        let db = Ledger::open_in_memory().unwrap();
        let d = ReceiptDraft {
            id: "r1".into(),
            captured_at: "2024-05-01T00:00:00Z".into(),
            merchant: Field::new("全家".into(), 1.0, FieldSource::User),
            total: Field::new(Money::new(8900, Iso4217::TWD), 1.0, FieldSource::User),
            transacted_at: Field::new("2024-05-01".into(), 1.0, FieldSource::User),
            tax: None,
            invoice_id: None,
            category: Field::new("grocery_convenience".into(), 1.0, FieldSource::User),
            raw_text: String::new(),
            ocr_blocks: vec![],
            overall_confidence: 1.0,
            explain: crate::ExplainTrace::new("t", "ocr"),
            source_path: SourcePath::Manual,
        };
        db.confirm_draft(&d, None, None, false).unwrap();
        let md = monthly_markdown(&db, 2024, 5).unwrap();
        assert!(md.contains("2024-05"));
        assert!(md.contains("TWD"));
        assert!(md.contains("全家"));
    }
}
